# Generated by Django 3.0.6 on 2020-05-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publish',
            name='file',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
