# Generated by Django 3.0.6 on 2020-05-07 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_publish_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='admin2',
        ),
    ]
