# Generated by Django 3.0.6 on 2020-05-07 17:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admins', '0003_delete_admin2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admin3',
            new_name='adminlevel',
        ),
    ]
